version: '3.6'
networks:
    mocker_network:

services:
    api:
        build: .
        container_name: mocker_api
        restart: always
        env_file:
            - './env/docker.env'
        ports:
            - "8080:8080"
        networks:
            - mocker_network
        depends_on:
            - postgres
            - migrations
        networks:
            - mocker_network
        depends_on:
            - postgres
    postgres:
        container_name: mocker_postgres
        image: postgres
        networks:
            mocker_network:
                aliases:
                    - "postgres.docker.local"
        volumes:
            - "./tmp/postgres:/var/lib/postgresql/data"
            - "./tools/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh"
        ports:
            - "5432:5432"
